spring:
  application:
    name: security-02-db-login

  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/dlyk
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.zw.entity
  mapper-locations: classpath:/mapper/*.xml